services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: jobapp-frontend:local
    container_name: jobapp-frontend-local
    ports:
      - "3002:80"
    environment:
      API_URL: "/api"
      API_UPSTREAM: "http://jobapp-backend-local:8080"
    restart: unless-stopped
    networks:
      - jobapp-net-local

networks:
  jobapp-net-local:
    external: true